version: "3.8"

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - "./ci/bootstrap_test_db.sh:/docker-entrypoint-initdb.d/bootstrap_test_db.sh"

  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - "8080:8080"
